//register.reducer
export const TOGGLE_TERMS = 'TOGGLE_TERMS'
export const REGISTER_CHANGE_FIELD = 'REGISTER_CHANGE_FIELD'
export const REGISTER_CHECK_FIELD = 'REGISTER_CHECK_FIELD'
//login.reducer
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_CHANGE_FIELD = 'LOGIN_CHANGE_FIELD'
export const FORGOTPASS_SHOW = 'FORGOTPASS_SHOW'
export const FORGOTPASS_HIDE = 'FORGOTPASS_HIDE'
/* //user.reducer
export const TOGGLE_TERMS = 'TOGGLE_TERMS'
export const REGISTER_CHANGE_FIELD = 'REGISTER_CHANGE_FIELD'
export const REGISTER_CHECK_FIELD = 'REGISTER_CHECK_FIELD' */
//app.reducer
export const ALERT_SUCCESS = 'ALERT_SUCCESS'
export const ALERT_FAIL = 'ALERT_FAIL'
export const ALERT_CLOSE = 'ALERT_CLOSE'
export const PROGRESS_SHOW = 'PROGRESS_SHOW'
export const PROGRESS_HIDE = 'PROGRESS_HIDE'
//language.reducer
export const LOCALIZATION_SET = 'LOCALIZATION_SET'
export const TOGGLE_LOCALIZATION_BAR = 'TOGGLE_LOCALIZATION_BAR'